name: Deploy Frontend

on:
  push:
    branches: [ main ]
    workflow_dispatch:
    paths:
      - 'frontend/**'

jobs:
  deploy-frontend:
    uses: jayapraveenasrinivasan0315-afk/task1/.github/workflows/_reusable-deploy.yml@main
    with:
      deployment_type: frontend
      environment: development
      app_path: frontend
      app_name: frontend-app
      artifact_name: frontend-build
      region: asia-south1
      secrets: inherit
