name: Release
on:
  workflow_dispatch:
jobs:
  release:
    uses: jayapraveenasrinivasan0315-afk/cherry-pick/.github/workflows/release.yml@main
    with:
      app_name: frontend
      base_branch: production
    secrets:
      GH_TOKEN: ${{ secrets.GH_PAT }}

    
